version: "3"
services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    networks:
      - app-network
    environment:
      - DATABASE_URL=postgresql://postgres:password@db:5432/app_db

  frontend:
    build:
      context: ./frontend
    networks:
      - app-network

  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "80:80" 
    volumes:
      - ./frontend:/usr/share/nginx/html:ro 
      - ./frontend/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: app_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
